// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/board/[boardId]": InferRoute<import("./src/app/(default)/board/[boardId]/routeType").RouteType>;
    "/board/[boardId]/task/[taskId]": InferRoute<import("./src/app/(default)/board/[boardId]/task/[taskId]/routeType").RouteType>;
    "/dashboard/workspace/[id]/boards": InferRoute<import("./src/app/(default)/dashboard/workspace/[id]/boards/routeType").RouteType>;
    "/dashboard/workspace/[id]/members": InferRoute<import("./src/app/(default)/dashboard/workspace/[id]/members/routeType").RouteType>;
    "/dashboard/workspace/[id]/settings": InferRoute<import("./src/app/(default)/dashboard/workspace/[id]/settings/routeType").RouteType>;
    "/auth/sign-in": InferRoute<import("./src/app/auth/sign-in/routeType").RouteType>;
    "/auth/sign-up": InferRoute<import("./src/app/auth/sign-up/routeType").RouteType>;
  }

  interface StaticRouter {
    "/dashboard/boards": StaticRoute;
    "/dashboard/main": StaticRoute;
    "/dashboard": StaticRoute;
    "/": StaticRoute;
  }
}
